import type { AtlasDef } from "../atlasConfig.ts";

export const MayAtlas: AtlasDef = {
    compress: true,
    images: [
        "map/lasr_Swrds_Crate.svg",
        "map/lasr_swrds_bush.svg",
        "map/lasr_swrds_tree_01.svg",
        "map/lasr_swrds_tree_02.svg",
        "map/map-bunker-conch-chamber-floor-lasr-01.svg",
        "map//map-bunker-conch-chamber-floor-lasr-02.svg",
        "map/map-bunker-conch-compartment-floor-01a-lasr.svg",
        "map/map-bunker-crossing-compartment-floor-01-lasr.svg",
        "map/map-bunker-crossing-chamber-floor-lasr.svg",
        "map/map-bunker-crossing-compartment-floor-lasr.svg",
        "map/map-bunker-crossing-floor-01-lasr.svg",
        "map/space_crate.svg",
        // (reminder) remove unused image later
        "map/map-building-greenhouse-ceiling-01.svg",
        "map/map-building-greenhouse-floor-01.svg",
        "map/map-bunker-chrys-chamber-ceiling-01.svg",
        "map/map-bunker-chrys-chamber-floor-01a.svg",
        "map/map-bunker-chrys-chamber-floor-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-01a.svg",
        "map/map-bunker-chrys-compartment-ceiling-01b.svg",
        "map/map-bunker-chrys-compartment-ceiling-02a.svg",
        "map/map-bunker-chrys-compartment-ceiling-02b.svg",
        "map/map-bunker-chrys-compartment-ceiling-03a.svg",
        "map/map-bunker-chrys-compartment-ceiling-03b.svg",
        "map/map-bunker-chrys-compartment-floor-01a.svg",
        "map/map-bunker-chrys-compartment-floor-01b.svg",
        "map/map-bunker-chrys-compartment-floor-02a.svg",
        "map/map-bunker-chrys-compartment-floor-02b.svg",
        "map/map-bunker-chrys-compartment-floor-03a.svg",
        "map/map-bunker-crossing-ceiling-01.svg",
        "map/map-bunker-crossing-chamber-ceiling-01.svg",
        "map/map-bunker-crossing-chamber-floor-01a.svg",
        "map/map-bunker-crossing-chamber-floor-01b.svg",
        "map/map-bunker-crossing-chamber-floor-01c.svg",
        "map/map-bunker-crossing-chamber-floor-02.svg",
        "map/map-bunker-crossing-chamber-floor-03.svg",
        "map/map-bunker-crossing-compartment-ceiling-01a.svg",
        "map/map-bunker-crossing-compartment-ceiling-01b.svg",
        "map/map-bunker-crossing-compartment-floor-01.svg",
        "map/map-bunker-crossing-compartment-floor-02.svg",
        "map/map-bunker-crossing-floor-01.svg",
        "map/map-bunker-generic-ceiling-02.svg",
        "map/map-bunker-generic-floor-03.svg",
        "map/map-bunker-hydra-ceiling-01.svg",
        "map/map-bunker-hydra-chamber-ceiling-01.svg",
        "map/map-bunker-hydra-chamber-ceiling-02.svg",
        "map/map-bunker-hydra-chamber-ceiling-03.svg",
        "map/map-bunker-hydra-chamber-floor-01a.svg",
        "map/map-bunker-hydra-chamber-floor-01b.svg",
        "map/map-bunker-hydra-chamber-floor-02.svg",
        "map/map-bunker-hydra-chamber-floor-03.svg",
        "map/map-bunker-hydra-compartment-ceiling-01.svg",
        "map/map-bunker-hydra-compartment-ceiling-02.svg",
        "map/map-bunker-hydra-compartment-ceiling-03.svg",
        "map/map-bunker-hydra-compartment-floor-01.svg",
        "map/map-bunker-hydra-compartment-floor-02.svg",
        "map/map-bunker-hydra-compartment-floor-03.svg",
        "map/map-bunker-hydra-floor-01.svg",
        "map/map-bunker-hydra-floor-04.svg",
        "map/map-complex-warehouse-floor-01.svg",
        "map/map-complex-warehouse-floor-02.svg",
        "map/map-complex-warehouse-floor-03.svg",
        "map/map-planter-01.svg",
        "map/map-planter-02.svg",
        "map/map-planter-03.svg",
        "map/map-planter-04.svg",
        "map/map-planter-05.svg",
        "map/map-planter-res-01.svg",

    ],
};

